name: shaperecon
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.15.4
  - pandas=0.23.4
  - tqdm=4.28.1
  - scikit-image=0.14.0
  - numba=0.41.0
  - opencv=3.4.2
  - pytorch=0.4.1
  - torchvision=0.2.1
  - tensorflow=1.5.1
  - trimesh=2.35.47
  - rtree=0.8.3
  - scikit-learn=0.20.1
